"DbUser" = "postgres"
"DbPassword" = "edvAer9LKf,1sUWVpJ23^.djtR60f0"
"DbName" = "app"
"DbPort" = "5432"
"DbHost" = "tech-challenge-rds-postgres.cluster-cotdfxtnulqs.us-west-2.rds.amazonaws.com"
"ListenHost" = "localhost"
"ListenPort" = "3000"