"DbUser" = "postgres"
"DbPassword" = "h_LW5EX^cfzudPxG8A-N3x6kGgvSYf"
"DbName" = "app"
"DbPort" = "5432"
"DbHost" = "tech-challenge-rds-postgres.cluster-cotdfxtnulqs.us-west-2.rds.amazonaws.com"
"ListenHost" = "localhost"
"ListenPort" = "3000"